import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '<src>/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ allClients }) {
  console.log(allClients)
  return (
    <>
      <Head>
        <title>Yard App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
          <div> 
              <h1>Hello Admin, login please!</h1>
              <form action='/api/hello' method='get'>
                <input type='text' placeholder='username'/>
                <input type='password' placeholder='password' /> 
                <button type='submit'>Login</button>
              </form>
          </div>
      </main> 
    </>
  )
}
